stages:
  - trigger
trigger:
  stage: trigger
  script:
    - apk add --no-cache --update-cache curl coreutils git
    - VERSION=$(git describe --abbrev=0 --tags | tr -d 'v')
    - curl -X POST -F "token=$GITLAB_CI_TRIGGER_TOKEN" -F "ref=es-client-staging" -F "variables[TRIGGERED_BY]=$CI_BUILD_REF_NAME" https://gitlab.glints.com/api/v3/projects/40/trigger/builds
  tags:
    - docker:docker
  only:
    - staging

